### PR TITLE
Some README formatting...

### PR DESCRIPTION
**Pull request by michaellihs**
Hi @ctrabold !

Ich hab mir erlaubt, deine README etwas zu "re-formatieren" - nix Großes, aber dachte, vielleicht freust du dich :-)

Soll "Hallo!" sagen von Michael Fait - habe gerade das Vergnügen, mit ihm zu hacken... erinnert ein wenig an die Zeit in Kambodscha...

Grüßle,

Mimi

### CODE REVIEW

**Comment by ctrabold** [comment]
:heart:

**Comment by visay** [comment]
:+1: even though I don't understand German but fortunately I can speak markdown language :dancers:

**Comment by michaellihs** [comment]
hey @visay great to hear you! How are you? Why do you read merge request comments on Github :-) Plz say hello to my friends at WebEssentials! We are doing fine and there will be a Mini-Lihs during the next couple of days... so excited...

**Comment by visay** [comment]
Congrats and we hope to see some photos afterwards of Mini-Lihs :) I'm doing good and will forward your greeting and good news to Web Essentials people.

I think I have involved in this repo before, that's why I got alert when you sent this PR.

**Pull request merged**
